# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  yarn:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.10.0-stretch-browsers-legacy

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - yarn-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    docker:
      - image: circleci/node:10.10.0-stretch-browsers-legacy
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Linting
          command: yarn lint

  unit-tests:
    docker:
      - image: circleci/node:10.10.0-stretch-browsers-legacy
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Unit Tests
          command: yarn test:unit

  build:
    docker:
      - image: circleci/node:10.10.0-stretch-browsers-legacy
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: yarn build:tsoa
      - persist_to_workspace:
          root: .
          paths:
            # This path can be used by other jobs
            - build

  deploy-dev:
      machine: true
      steps:
        - checkout
        - run:
            name: Build and push Docker image to development
            command: |
              docker build -t fabripautasso/node-starter-v2 .
              docker pull wagoodman/dive
              docker run --rm -it \
                -v /var/run/docker.sock:/var/run/docker.sock \
                wagoodman/dive:latest --ci fabripautasso/node-starter-v2 --lowestEfficiency=0.8 --highestUserWastedPercent=0.45
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push fabripautasso/node-starter-v2

workflows:
  version: 2

  test-build-deploy:
    jobs:
      - yarn
      - lint:
          requires:
            - yarn
      - unit-tests:
          requires:
            - yarn
      - build:
          requires:
            - yarn
      - deploy-dev:
          requires:
            - lint
            - unit-tests
            - build
          filters:
            branches:
              only: develop
